### ISSUE TITLE
[bug] Random video fails 

### ISSUE THREAD

**Issue by indiagolph99** [Nassim-Saboundji/MinimalTube-Web#1]
**Requirements:**
1. Linux machine
2. Chrome 80+

**Steps to reproduce:**
Example request is 'nora west allen'
![minitubebug1](https://user-images.githubusercontent.com/22380317/81124443-174eb580-8f3e-11ea-9f9a-10b594fb8075.png)

**Expected result:**
Video loads normally

**Actual result:**
see picture above

**How reproducable?**

unclear, seems to be depending on request

**Comment by Nassim-Saboundji** [comment]
I have fixed the issue. Now it should work.
